---
- name: Update version of splunkbase app in splunk cloud | {{ splunkbase_app.id }}
  ansible.builtin.uri:
    url: "https://{{ splunk_acs_domain }}/{{ splunk_cloud_stack }}/adminconfig/v2/apps/victoria/{{ f_splunkbase_app_config.name }}"
    method: PATCH
    body_format: form-urlencoded
    status_code: [200, 202]
    return_content: true
    headers:
      Content-Type: "application/x-www-form-urlencoded"
      X-Splunkbase-Authorization: "{{ f_splunkbase_sessionid }}"
      ACS-Licensing-Ack: "{{ splunkbase_app.license }}"
      Authorization: "Bearer {{ splunk_cloud_token }}"
    body:
      version: "{{ splunkbase_app.version }}"
  changed_when: r_update_app.json.status == "processing"
  register: r_update_app
  tags:
    - splunkbase_update_app
