---
# BUG? AppInspect gets permission denied if file doesnt exist
- name: Create AppInspect report file | {{ splunk_cloud_app_name }}
  ansible.builtin.file:
    path: "{{ splunk_cloud_appinspect_reports_folder }}/{{ splunk_cloud_app_name }}-appinspect-cli.json"
    mode: "644"
    state: touch

- name: Running local app-inspect | {{ splunk_cloud_app_name }}
  ansible.builtin.command: |
    splunk-appinspect inspect {{ splunk_cloud_app_path }}
    --included-tags=private_victoria
    --data-format json
    --output-file {{ splunk_cloud_appinspect_reports_folder }}/{{ splunk_cloud_app_name }}-appinspect-cli.json
  register: r_appinspect_output
  failed_when: r_appinspect_output.rc != 0
  changed_when: true

- ansible.builtin.debug:
    msg: "{{ r_appinspect_output }}"

- name: Get CLI AppInspect report | {{ splunk_cloud_app_name }}
  ansible.builtin.slurp:
    src: "{{ splunk_cloud_appinspect_reports_folder }}/{{ splunk_cloud_app_name }}-appinspect-cli.json"
  register: splunk_cloud_app_cli_report

- name: Output AppInspect CLI results | {{ splunk_cloud_app_name }}
  ansible.builtin.fail:
    msg:
      - "AppInspect CLI checks failed."
      - "Please see JSON report at {{ splunk_cloud_appinspect_reports_folder }}/{{ splunk_cloud_app_name }}-appinspect-cli.json for more info."
      - "{{ (splunk_cloud_app_cli_report['content'] | b64decode | from_json).summary }}"
  when: |
    (splunk_cloud_app_cli_report['content'] | b64decode | from_json).summary.failure > 0 or
    (splunk_cloud_app_cli_report['content'] | b64decode | from_json).summary.error > 0

- name: Create a tar.gz archive of the app folder | {{ splunk_cloud_app_name }}
  community.general.archive:
    path: "{{ splunk_cloud_app_path }}"
    dest: "/tmp/{{ splunk_cloud_app_name }}.tar.gz"
    format: gz
    force_archive: true
    mode: "644"
  register: r_splunk_app_archive

- name: Set facts
  ansible.builtin.set_fact:
    f_private_app_archive: "{{ r_splunk_app_archive.dest }}"

- name: Send app to validation | {{ splunk_cloud_app_name }} # noqa: command-instead-of-module
  ansible.builtin.command: |
    curl -s -X POST "https://appinspect.splunk.com/v1/app/validate"
    -F "app_package=@{{ f_private_app_archive }}"
    --header "Authorization: Bearer {{ r_splunk_api_login.json.data.token }}"
    -F "included_tags=private_victoria"
  delay: 15
  timeout: 30
  retries: 10
  register: r_splunk_validate_submit
  failed_when: r_splunk_validate_submit.rc!=0
  changed_when: r_splunk_validate_submit.rc==0

- name: Extract validation request id | {{ splunk_cloud_app_name }}
  ansible.builtin.set_fact:
    f_validation_id: "{{ (r_splunk_validate_submit.stdout | from_json).request_id }}"

- name: Check validation status | {{ splunk_cloud_app_name }}
  ansible.builtin.uri:
    url: "https://appinspect.splunk.com/v1/app/validate/status/{{ f_validation_id }}"
    method: GET
    return_content: true
    headers:
      Authorization: "Bearer {{ r_splunk_api_login.json.data.token }}"
  register: r_splunk_validate_status
  until: r_splunk_validate_status.json.status != "PROCESSING"
  retries: 100
  delay: 10

- name: Extract validation info | {{ splunk_cloud_app_name }}
  ansible.builtin.set_fact:
    f_splunk_validate_info: "{{ r_splunk_validate_status.json.info }}"

- name: Check if app passed the validation | {{ splunk_cloud_app_name }}
  ansible.builtin.set_fact:
    f_splunk_validate_passed: |
      {{ r_splunk_validate_status.json.status == "SUCCESS" and
      f_splunk_validate_info.error == 0 and
      f_splunk_validate_info.failure == 0 and
      f_splunk_validate_info.manual_check == 0 }}

- name: Get failure report (JSON) | {{ splunk_cloud_app_name }}
  ansible.builtin.get_url:
    url: "https://appinspect.splunk.com/v1/app/report/{{ f_validation_id }}"
    dest: "{{ splunk_cloud_appinspect_reports_folder }}/{{ splunk_cloud_app_name }}.json"
    mode: "644"
    headers:
      Authorization: "Bearer {{ r_splunk_api_login.json.data.token }}"
      Content-Type: "application/json"
  register: app_report_json_file
  when: not f_splunk_validate_passed

- name: Get failure report (HTML) | {{ splunk_cloud_app_name }}
  ansible.builtin.get_url:
    url: "https://appinspect.splunk.com/v1/app/report/{{ f_validation_id }}"
    dest: "{{ splunk_cloud_appinspect_reports_folder }}/{{ splunk_cloud_app_name }}.html"
    mode: "644"
    headers:
      Authorization: "Bearer {{ r_splunk_api_login.json.data.token }}"
      Content-Type: "text/html"
  register: app_report_json_file
  when: not f_splunk_validate_passed

- name: Fail when app validation does not pass | {{ splunk_cloud_app_name }}
  ansible.builtin.fail:
    msg: "Validation not passed - see {{ splunk_cloud_appinspect_reports_folder }} folder for appinspect details"
  when: not f_splunk_validate_passed
