name: deploy egress config
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "inventory/host_vars/*/egress_allowlist.yml"

concurrency:
  group: ${{ github.workflow }}

jobs:
  ansible:
    name: deploy egress config
    uses: ./.github/workflows/ansible-playbook.yml
    with:
      ansible_playbook: cloud_egress_allow.yml
      ansible_inventory: inventory
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
      SPLUNKBASE_USERNAME: ${{ secrets.SPLUNKBASE_USERNAME }}
      SPLUNKBASE_PASSWORD: ${{ secrets.SPLUNKBASE_PASSWORD }}
      SPLUNK_TOKEN: ${{ secrets.SPLUNK_TOKEN }}
